apiVersion: v1
kind: Namespace
metadata:
  name: crdsdev
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: doc-repos
  namespace: crdsdev
data:
  repos: "crossplane/crossplane,crossplane/provider-gcp,crossplane/provider-aws,crossplane/provider-azure,crossplane/provider-alibaba,crossplane/provider-rook,crossplane-contrib/provider-helm,kubernetes-sigs/cluster-api,jetstack/cert-manager,schemahero/schemahero,projectcontour/contour,packethost/crossplane-provider-packet,kubernetes-sigs/cluster-api-provider-packet,crossplane/oam-kubernetes-runtime,kubernetes-sigs/security-profiles-operator"
